In [1]:
import os

os.environ["SEED"] = "0"

import cocoex
import matplotlib.pyplot as plt
import nevergrad as ng
import numpy as np
import scipy

from src.solver.BBOB_POP_Solver import BBOB_POP_Solver
from src.instance.BBOB_Instance import BBOB_Instance

In [2]:
suite = cocoex.Suite("bbob", "", "function_indices:1 dimensions:2 instance_indices:1-15")

In [3]:
suite

Suite(b'bbob', b'', b'function_indices:1 dimensions:2 instance_indices:1-15')

In [4]:
len(list(suite))
# 6 dimensions X 24 functions X 15 instances = 2160 problems

15

In [5]:
problem = suite[0]
problem.info

'bbob_f001_i01_d02: a 2-dimensional single-objective problem (problem 0 of suite "b\'bbob\'" with name "BBOB suite problem f1 instance 1 in 2D")'

In [8]:
instance = BBOB_Instance(problem, cut_off_cost=1.0, cut_off_time=0.1)
instance

TypeError: no default __reduce__ due to non-trivial __cinit__

In [ ]:

solver = BBOB_POP_Solver()
print(solver.config)

kwargs = dict(solver.config)
algorithm = solver.config["ALGORITHM"]

def _format_key(key: str, algorithm) -> str:
    key = key[len(algorithm) + 1:]
    if not (algorithm == "DE" and key in ["F1", "F2"]):
        key = key.lower()
    return key

kwargs = {_format_key(k, algorithm): v for k, v in kwargs.items() if k.startswith(algorithm)}

if algorithm == "PSO":
    optimizer_class = ng.families.ConfPSO(**kwargs)
elif algorithm == "DE":
    optimizer_class = ng.families.DifferentialEvolution(**kwargs)
elif algorithm == "CMA":
    optimizer_class = ng.families.ParametrizedCMA(**kwargs)
else:
    raise ValueError(f"Unknown algorithm: {algorithm}")

optimizer = optimizer_class(parametrization=instance.dimension, budget=1e6)
recommendation = optimizer.minimize(problem, max_time=instance.cut_off_time)
recommendation.value, problem.evaluations, problem.final_target_hit

TypeError: no default __reduce__ due to non-trivial __cinit__

In [7]:
problem = suite[0]

In [36]:
problem.dimension

2

In [8]:
problem.evaluations

0

In [9]:
problem.final_target_hit

False

In [ ]:
pso_config = ng.families.ConfPSO(
    popsize=20,           # Population size
    omega=0.729,          # Inertia weight
    phip=1.49618,         # Cognitive parameter
    phig=1.49618,         # Social parameter
)

optimizer = pso_config(2, budget=1000)

recommendation = optimizer.minimize(problem)
recommendation.value

array([ 0.25222357, -1.15669464])

In [11]:
scipy.optimize.fmin(problem, problem.initial_solution, disp=True)

Optimization terminated successfully.
         Current function value: 79.480000
         Iterations: 65
         Function evaluations: 124


array([ 0.25281244, -1.15682905])

In [12]:
problem.evaluations

1124

In [13]:
problem.final_target_hit

True

In [24]:
problem = suite[0]

pso_config = ng.families.ConfPSO(
    popsize=20,           # Population size
    omega=0.729,          # Inertia weight
    phip=1.49618,         # Cognitive parameter
    phig=1.49618,         # Social parameter
)

optimizer = pso_config(2, budget=100)

recommendation = optimizer.minimize(problem, max_time=100)
recommendation.value, problem.evaluations, problem.final_target_hit

(array([ 0.15684738, -1.09546823]), 100, False)

In [34]:
problem = suite[0]

de_config = ng.families.DifferentialEvolution(
    popsize=20,
    crossover=0.8,
)

optimizer = de_config(2, budget=10000)

recommendation = optimizer.minimize(problem, max_time=1)
recommendation.value, problem.evaluations, problem.final_target_hit

(array([ 0.25279718, -1.15679968]), 2851, True)

In [14]:
suite = cocoex.Suite("bbob", "", "function_indices:1 dimensions:2 instance_indices:1-15")

for problem in suite:
    xopt = fmin(problem, problem.initial_solution, disp=True)
    print(problem.final_target_hit)

Optimization terminated successfully.
         Current function value: 79.480000
         Iterations: 65
         Function evaluations: 124
True
Optimization terminated successfully.
         Current function value: 394.480000
         Iterations: 71
         Function evaluations: 138
True
Optimization terminated successfully.
         Current function value: -247.110000
         Iterations: 71
         Function evaluations: 139
True
Optimization terminated successfully.
         Current function value: -152.040000
         Iterations: 72
         Function evaluations: 141
True
Optimization terminated successfully.
         Current function value: -25.250000
         Iterations: 58
         Function evaluations: 114
True
Optimization terminated successfully.
         Current function value: 183.010000
         Iterations: 78
         Function evaluations: 149
True
Optimization terminated successfully.
         Current function value: 183.520000
         Iterations: 71
         Function